export PATH="~/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export PS1="\[\e]2;local/\w |\a\]\[\e[30;42m\]:\[\e[0m\] "
alias mysql.server=/usr/local/mysql/share/mysql/mysql.server
alias la="ls -la"
alias ls="ls -G"
alias tl="TimeLog"
alias tr="TimeReport"
alias sinatra="ruby -rubygems"
alias proj=". cd_masked ~/projects/%1*/www"
