#!/bin/bash

cd "$(dirname $0)"

git pull
git submodule init
git submodule update

# Clean out any outdated symlinks from ~
for file in $(ls -A ~); do
  # If $file
  # - is a symlink
  # - that points to a nonexistent file
  # - somewhere inside this directory
  # Then rm it
  [[ -h ~/$file ]] && [[ ! -e ~/$file ]] && [[ $(ls -l ~/$file) == *$(pwd)* ]] && rm ~/$file
done

# Add all the latest symlinks into ~
for file in $(ls -A | grep -v "^\.skipfiles$" | grep -vf .skipfiles); do
  if [[ -e ~/$file ]] && [[ ! -h ~/$file ]]; then
    echo "skipping ~/$file, as it already exists"
  else
    ln -fs $(pwd)/$file ~/
  fi
done

cd - >/dev/null

source ~/.profile
